name: Scrape and Update Showtimes
permissions:
  contents: write



on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours (UTC)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run scraper
        run: python maine_showtimes_scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add maine_showtimes.json
          git commit -m "Update showtimes [auto]" || echo "No changes to commit"
          git push